mm:
    encrypt:
        password: ChangeMe
    elasticsearch:
        embedded: true
        address: localhost
        port: 9300
        cluster:
            name: elasticsearch
    plugin:
        defaultStartDate: 08/07/2015
eureka:
    client:
        enabled: false
spring:
    application:
        name: measurementor
---
spring:
    profiles: vagrant
mm:
    elasticsearch:
        embedded: false
        address: localhost
---
spring:
    profiles: docker
mm:
    elasticsearch:
        embedded: false
---
spring:
    profiles: prod
mm:
    encrypt:
        password: ChangeMe
    elasticsearch:
        embedded: false
        address: apollo-elasticsearch.tools.nikecloud.com
        port: 9300
        cluster:
            name: apolloelasticsearch